#sql server
#spring.datasource.url: jdbc:sqlserver://localhost:1433;databaseName=ssi
#spring.datasource.username: sa
#spring.datasource.password: sapassword
#spring.datasource.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql: true
#spring.jpa.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.hibernate.ddl-auto: validate
# H2
#spring.h2.console.enabled: true
#spring.h2.console.path: /h2
#security.headers.frame: false

# Connection url for the database
spring.datasource.url: jdbc:mysql://192.168.200.50:3306/ssi

# Fully qualified name of JDBC driver. Auto-detected based on the URL
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

# Username & password db
spring.datasource.username: root
spring.datasource.password: root

# ==================
# JPA/HIBERNATE
# ===================

# Show or not log for sql queries
#spring.jpa.show-sql=true

# Hibernate ddl auto(create, create-drop, update) : with "update"
# the database schema will be automatically updated according to java
# entities found in the project
spring.jpa.hibernate.ddl-auto: create-drop


#security configuration
security.oauth2.resource.filter-order: 3
security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT Example Realm
  jwt:
    client-id: testjwtclientid
    client-secret: XY7kmzoNzl100
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid
#spring:
#  datasource:
#    url: jdbc:h2:mem:sisdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
